version: "3.9"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      LANG: C.utf8
      LC_ALL: C.utf8
    ports:
      - "5432:5432"
